### ISSUE TITLE
LiveDirectory for static assets in Hyper-Express sometimes does leaves connection hanging

### ISSUE THREAD

**Issue by MichaelJCole** [kartikk221/live-directory#1] opened 2021-12-29 20:30 UTC
Hello, I am trying to use LiveDirectory to serve static assets with Hyper-Express like this:

```
const LiveAssets = new LiveDirectory({ path: './public' });
app.get('/*',(req, res) => {
  const found = LiveAssets.get(req.path);
  if (!found) return res.status(404).send();
  res.type(found.extension).send(found.buffer);
});
```

I am working on integrating passportjs with hyper-express based on the passportjs example I forked here:

https://github.com/MichaelJCole/hyper-express-sessions-passport-local

When I start the server and reload in chrome, almost always the server connections hang on some of the static assets.  If I reload 20ish times, the assets server just fine.

To reproduce, try the master branch.  I'm using node 14.18.1.  Firefox 95.0.2.

![image](https://user-images.githubusercontent.com/1504790/147700841-c8236a42-9236-4f4d-9768-2b1668b13763.png)

Am I using this wrong?  Thank you!

**Comment by kartikk221** [comment] 2021-12-29 20:38
The snippet you posted above looks fine so there is likely some problem in one of your middlewares which are not continuing their execution. I would say look through all of your middlewares and check to see that you are calling the next() parameter callback or resolving any await promises inside of async middlewares. To narrow down to which middleware is causing the problem, try commenting out the `use()` calls to each middleware until the problem is resolved.

**Comment by MichaelJCole** [comment] 2021-12-29 20:39
Hi Kartik, I just moved this to: https://github.com/kartikk221/hyper-express/issues/42.  Ok, I'll try that out and comment there.  Thank you!

**Closed as completed** 2021-12-29 20:39 UTC
